# Generated by Django 4.1.1 on 2022-10-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obat',
            fields=[
                ('idobat', models.AutoField(primary_key=True, serialize=False)),
                ('jenisobat', models.CharField(max_length=50)),
                ('namaobat', models.CharField(max_length=10)),
                ('hargabeli', models.IntegerField()),
                ('hargajual', models.IntegerField()),
                ('satuan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='penjualan',
            fields=[
                ('idpenjualan', models.AutoField(primary_key=True, serialize=False)),
                ('namaapoteker', models.CharField(max_length=50)),
                ('namapelanggan', models.CharField(max_length=50)),
                ('tanggaltransaksi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('idsupplier', models.AutoField(primary_key=True, serialize=False)),
                ('namasupplier', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('nohp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pembelian',
            fields=[
                ('idpembelian', models.AutoField(primary_key=True, serialize=False)),
                ('namaapoteker', models.CharField(max_length=50)),
                ('tanggalpembelian', models.DateField()),
                ('idsupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='detailpenjualan',
            fields=[
                ('iddetailpenjualan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahobatterjual', models.IntegerField()),
                ('idobat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obat')),
                ('idpenjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjualan')),
            ],
        ),
        migrations.CreateModel(
            name='detailpembelian',
            fields=[
                ('iddetailpembelian', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahobatdibeli', models.IntegerField()),
                ('idobat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obat')),
                ('idpembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembelian')),
            ],
        ),
    ]
